//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RpcProto.proto
namespace RpcProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Customer")]
  public partial class Customer : global::ProtoBuf.IExtensible
  {
    public Customer() {}
    
    private string _firstName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"firstName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string firstName
    {
      get { return _firstName; }
      set { _firstName = value; }
    }
    private string _lastName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lastName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string lastName
    {
      get { return _lastName; }
      set { _lastName = value; }
    }
    private int _age = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"age", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int age
    {
      get { return _age; }
      set { _age = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostCustomerRequest")]
  public partial class PostCustomerRequest : global::ProtoBuf.IExtensible
  {
    public PostCustomerRequest() {}
    
    private Customer _customer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"customer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Customer customer
    {
      get { return _customer; }
      set { _customer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetCustomerRequest")]
  public partial class GetCustomerRequest : global::ProtoBuf.IExtensible
  {
    public GetCustomerRequest() {}
    
    private readonly global::System.Collections.Generic.List<Customer> _customers = new global::System.Collections.Generic.List<Customer>();
    [global::ProtoBuf.ProtoMember(1, Name=@"customers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Customer> customers
    {
      get { return _customers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeleteCustomerRequest")]
  public partial class DeleteCustomerRequest : global::ProtoBuf.IExtensible
  {
    public DeleteCustomerRequest() {}
    
    private Customer _customer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"customer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Customer customer
    {
      get { return _customer; }
      set { _customer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}