//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RpcProto.proto
namespace RpcProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Customer")]
  public partial class Customer : global::ProtoBuf.IExtensible
  {
    public Customer() {}
    
    private string _firstName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"firstName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string firstName
    {
      get { return _firstName; }
      set { _firstName = value; }
    }
    private string _lastName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lastName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string lastName
    {
      get { return _lastName; }
      set { _lastName = value; }
    }
    private int _age = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"age", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int age
    {
      get { return _age; }
      set { _age = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostCustomerRequest")]
  public partial class PostCustomerRequest : global::ProtoBuf.IExtensible
  {
    public PostCustomerRequest() {}
    
    private int _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private RequestType _method;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"method", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RequestType method
    {
      get { return _method; }
      set { _method = value; }
    }
    private Customer _customer;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"customer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Customer customer
    {
      get { return _customer; }
      set { _customer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostCustomerResponse")]
  public partial class PostCustomerResponse : global::ProtoBuf.IExtensible
  {
    public PostCustomerResponse() {}
    
    private int _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private int _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetCustomerRequest")]
  public partial class GetCustomerRequest : global::ProtoBuf.IExtensible
  {
    public GetCustomerRequest() {}
    
    private int _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private RequestType _method;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"method", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RequestType method
    {
      get { return _method; }
      set { _method = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetCustomerResponse")]
  public partial class GetCustomerResponse : global::ProtoBuf.IExtensible
  {
    public GetCustomerResponse() {}
    
    private int _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private int _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<Customer> _customers = new global::System.Collections.Generic.List<Customer>();
    [global::ProtoBuf.ProtoMember(3, Name=@"customers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Customer> customers
    {
      get { return _customers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeleteCustomerRequest")]
  public partial class DeleteCustomerRequest : global::ProtoBuf.IExtensible
  {
    public DeleteCustomerRequest() {}
    
    private int _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private RequestType _method;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"method", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RequestType method
    {
      get { return _method; }
      set { _method = value; }
    }
    private Customer _customer;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"customer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Customer customer
    {
      get { return _customer; }
      set { _customer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeleteCustomerResponse")]
  public partial class DeleteCustomerResponse : global::ProtoBuf.IExtensible
  {
    public DeleteCustomerResponse() {}
    
    private int _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private int _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private int _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private RequestType _method;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"method", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RequestType method
    {
      get { return _method; }
      set { _method = value; }
    }
    private GetCustomerRequest _get = null;
    [global::ProtoBuf.ProtoMember(101, IsRequired = false, Name=@"get", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GetCustomerRequest get
    {
      get { return _get; }
      set { _get = value; }
    }
    private PostCustomerRequest _post = null;
    [global::ProtoBuf.ProtoMember(102, IsRequired = false, Name=@"post", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PostCustomerRequest post
    {
      get { return _post; }
      set { _post = value; }
    }
    private DeleteCustomerRequest _delete = null;
    [global::ProtoBuf.ProtoMember(103, IsRequired = false, Name=@"delete", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DeleteCustomerRequest delete
    {
      get { return _delete; }
      set { _delete = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RequestType")]
    public enum RequestType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Unknown", Value=0)]
      Unknown = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetCustomers", Value=1)]
      GetCustomers = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PostCustomer", Value=2)]
      PostCustomer = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DeleteCustomer", Value=3)]
      DeleteCustomer = 3
    }
  
}